### ISSUE TITLE
Support versions of MacOS before 10.14

### ISSUE THREAD

**Issue by leighsmith** [leighsmith/midisport-macos#10]
In principle, there is little preventing the driver from running on earlier versions of MacOS X than Mojave. Perhaps a fat binary is needed for 32 and 64 bit versions, and the build specs (and installer Distribution.xml OS version minimum) would need to be set for earlier versions. If anyone has an earlier version of MacOS and would to test?

**Comment by project707** [comment]
Yeah the old M-Audio driver actually ran with no problem for me and many others (confirmed by a well known synth manufacturer's team lead that I discussed it with the other day), up to and including Mojave.
