### ISSUE TITLE
Digi 002 rack support

### ISSUE THREAD

**Issue by FreQRiDeR** [leighsmith/midisport-macos#11]
This is great! Thank You! Can you write a 64 bit driver form Digi 002 rack now??? Please! ;)
Great work!

FreQRiDeR

**Comment by leighsmith** [comment]
Obviously this would be separate project as the Digi 002 rack is a different device (ADC/DAC, not MIDI). As I don't possess such a device, and it would take significant time to reverse engineer the driver, I'm closing this ticket. I would suggest looking for Linux driver support for the device, as this would be the way to then create a CoreAudio driver from that reference.
