### ISSUE TITLE
Big Sur and M1

### ISSUE THREAD

**Issue by njc235** [leighsmith/midisport-macos#12]
I was very excited to stumble upon this project this morning having consigned my Midisport 2x2 to the relics shelf (probably where I should be too as it happens).  I hoped that it might work with my new M1 Big Sur MacMini and whilst the signs were good, the little LED pulsed on the green box and something was flashing on the In-B (where my Rland JV30 is), nothing came through to the MacMini.  I'm not asking fr or expecting anything from you fantastic developers, this is purely feedback for you.  Back to the relics shelf, for now at least.

**Comment by leighsmith** [comment]
Thanks for the report. There are two programs running in this project, the firmware downloader and the CoreMIDI driver. The pulsing USB LED indicates the firmware downloader indeed runs, but if you are not receiving MIDI data, then there is an issue with the CoreMIDI driver. At the moment, the current package is only compiled with Intel x86_64 architecture, but when there is a chance to build for Big Sur, we'll build for both architectures (as a fat binary).

**Comment by lhondareyte** [comment]
Hi all. For your convenience, I have just compile the package for BigSur (universal binary). It works just fine on apple Silicon M1. The package is [available here](http://lhondareyte.free.fr/Downloads/Rudix/MIDISPORTDriver-v1.2.0.pkg).
Leigh, thanks  for your work

**Comment by njc235** [comment]
You are a hero!!!!

**Comment by leighsmith** [comment]
Thanks @lhondareyte! The main distribution v1.2.0 available on SourceForge now includes the M1 Apple Silicon and Intel fat binaries as v1.2.0, also. So no need to keep hosting that driver, but your work is very much appreciated verifying it works!
