### ISSUE TITLE
Midisport 2x2 does't work on Mac Mini M1 (2020) OS X 11.6

### ISSUE THREAD

**Issue by Sprengart** [leighsmith/midisport-macos#25]
The Midisport wasn't recognized. The OS X was a clean install. Only system updates from Apple. Downloaded MIDISPORTDriver-v1.2.0.pkg and performed the installing. MIDISPORT.plugin is the only driver inside of library->Audio->Midi Drivers.
Before installing the MIDISortDriver I've installed following utilities that are dealing with Midi:
MidiPipe.app (1.6.2) and Midi Monitor.
Programs with access to Midi:
Arturia Software Center and Pigments, Native Instruments Guitar Rig 6, Behringer Synthtribe V2.5.5, Moog Model15.app, Ableton Live 11, Garageband, SysEx Librarian.
Any hints on that?
Regards Michael

**Comment by fvogel** [comment]
I had some similar issues from time to time, but I am not on M1 and I connect an Oxygen8.

Does the Midi Studio app recognize the Midisport? (just to make sure)
Have you tried another USB cable? In my case, for a reason I can't explain yet, I found only one old USB cable that would allow my Oxygen8 to show in Midi Studio successfully.

**Comment by Sprengart** [comment]
Another day, another Cable and, tatata, the USB-LED starts blinking. Look where it ends. thank you.
