### ISSUE TITLE
Downloaded /MIDISPORTDriver-v1.3.0.pkg on Mojave but it blew away my CORE Midi

### ISSUE THREAD

**Issue by musicmez** [leighsmith/midisport-macos#37]
Hi there, I did read that this may not work on Mojave but since it has corrupted my CORE midi (cannot launch Audio Midi Setup and Cubase 12 gets stuck on loading CORE Midi, I would like to uninstall this.  Any help would be appreciated.

Thank you,
 Steve

**Comment by musicmez** [comment]
Sorry for the confusion but I meant to say Monterey, not Mojave in my post. I may have resolved the issue by re-downloading and allowing to install Derez? Seems OK now in Monterey.

**Comment by leighsmith** [comment]
Ok, assuming you are still running the driver ok with Monterey (MacOS 12.X), can I close this issue?

**Comment by musicmez** [comment]
Yes you can close this. The reinstall seemed to work. Thank you.
