### ISSUE TITLE
Support for macOS 10.15+ with the new USB Host API

### ISSUE THREAD

**Issue by porg** [leighsmith/midisport-macos#4]
Thanks for providing software support for an abandoned piece of hardware! Very appreciated!

Your readme mentions macOS 10.15+ support for it's roadmap.
I create this issue that any progress can be observed by means of Github notification by interested users such as me.

Thanks!

**Comment by leighsmith** [comment]
I've now upgraded and verified that Catalina does indeed work with the current code, without needing to upgrade to the new USB Host API. Whether that is the case for Big Sur is another question.

**Comment by leighsmith** [comment]
OK, I've now released an Apple installer package that will install and run on MacOS v10.14 & v10.15. That is now linked from the README, and the package file itself is located at [sourceforge](https://sourceforge.net/projects/midisport-macos/files/latest/download). Once I have MacOS v11, Big Sur running, I'll look to support that too.

**Comment by leighsmith** [comment]
Ok Big Sur has been verified to work with v1.2.0, without needing the driver upgrade, so I'm closing this ticket.
