### ISSUE TITLE
I´m not certain how to build the pkg or how to run the installer for the driver

### ISSUE THREAD

**Issue by Morriscet** [leighsmith/midisport-macos#6]
i really appreciate @leighsmith  if you could help me, i´m not really into programming cuz i´m a producer however i really need to get to run my midisport 4x4 into catalina. I´ve read at least everything you posted and all forums but i cannot figure this out what to do after unzipping the bunch of files you got available for downloading. In the instructions you mentioned something about the midisport.pkg, are you talking abut the official installer from m-audio 3.5.3 or i have to build it out of the files you posted?

Thanks for your support

**Comment by leighsmith** [comment]
Hi, thanks so much for your interest in the project. There was some extra work required to produce a modern .pkg file, which is now linked from the README, and the package file itself is located at [sourceforge](https://sourceforge.net/projects/midisport-macos/files/latest/download).
